# Generated by Django 5.1.6 on 2025-05-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
