# Generated by Django 5.1.6 on 2025-05-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='public',
        ),
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=False, verbose_name='Disponible'),
        ),
    ]
