# Generated by Django 5.1.6 on 2025-05-18 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_products', '0002_remove_products_public_products_available'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
    ]
