# Generated by Django 5.1.6 on 2025-05-02 20:17

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(verbose_name='Nombre')),
                ('last_name', models.CharField(verbose_name='Apellidos')),
                ('phone', models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Introduzca un número de teléfono válido.', regex='^\\+\\d{10,15}$')], verbose_name='Teléfono')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('municipality', models.CharField(max_length=100, verbose_name='Municipio')),
                ('address', models.CharField(max_length=255, verbose_name='Dirección')),
                ('delivery_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio de Entrega')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('sended', 'Enviada'), ('completed', 'Completada'), ('canceled', 'Cancelada')], default='Pendiente', max_length=50, verbose_name='Estado')),
                ('invoice_file', models.FileField(upload_to='invoices/', verbose_name='Archivo de Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Carrito Activo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_store.cart', verbose_name='Carrito')),
                ('product', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_products.products', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Producto del carrito',
                'verbose_name_plural': 'Productos del carrito',
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(default=' ', through='app_store.CartItem', to='app_products.products', verbose_name='Productos'),
        ),
        migrations.CreateModel(
            name='InvoiceProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(verbose_name='ID del Producto')),
                ('product_name', models.CharField(verbose_name='Nombre del Producto')),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio del Producto')),
                ('product_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Descuento del Producto')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_store.invoices', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Producto de Factura',
                'verbose_name_plural': 'Productos de Factura',
                'unique_together': {('invoice', 'product_id')},
            },
        ),
    ]
