# Generated by Django 5.1.6 on 2025-05-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='delivery_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalles de Entrega'),
        ),
    ]
