# Generated by Django 5.1.6 on 2025-05-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_invoices_delivery_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
