# Generated by Django 5.1.6 on 2025-05-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0003_rename_phone_invoices_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('sended', 'Enviada'), ('completed', 'Completada'), ('canceled', 'Cancelada')], default='pending', max_length=50, verbose_name='Estado'),
        ),
    ]
