# Generated by Django 5.1.6 on 2025-05-18 21:46

import private_storage.fields
import private_storage.storage.files
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0004_alter_invoices_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='invoice_file',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='invoices/', verbose_name='Factura'),
        ),
    ]
