# Generated by Django 5.1.6 on 2025-03-18 03:43

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dni_number', models.CharField(unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', message='El DNI debe ser una cadena de 11 dígitos numéricos.')], verbose_name='Carnet de Identidad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('first_name', models.CharField(verbose_name='Nombre')),
                ('last_name', models.CharField(verbose_name='Apellidos')),
                ('phone_number', models.CharField(blank=True, null=True, validators=[django.core.validators.RegexValidator(message='Introduzca un número de teléfono válido.', regex='^\\+\\d{10,15}$')], verbose_name='Teléfono')),
                ('address', models.CharField(verbose_name='Dirección Particular')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='Correo Verificado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Superusuario')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_auth.user',),
        ),
    ]
