# Generated by Django 5.1.6 on 2025-04-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, null=True, verbose_name='Dirección Particular'),
        ),
    ]
