# Generated by Django 5.1.6 on 2025-04-08 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dni_number',
        ),
    ]
