# Generated by Django 5.1.6 on 2025-03-07 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0002_user_is_email_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
