"""
Django settings for trd_caribe project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from django.urls import reverse_lazy
from django.templatetags.static import static
from django.utils.translation import gettext_lazy as _
from dotenv import load_dotenv
from decouple import config

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9o3zfoz_j1-rf)h&!d(=-_wu9b#-f6#vuv@%!fnz+z)oae@&w)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG",default=True,cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'unfold',
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'private_storage',
    'app_auth',
    'app_config',
    'app_products',
    'app_store',
    'app_statistics',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trd_caribe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trd_caribe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES={
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DATABASE_NAME', default='trd_caribe'),
        'USER': config('DATABASE_USER', default='postgres'),
        'PASSWORD': config('DATABASE_PASSWORD',default='postgres'),
        'HOST': config('DATABASE_HOST',default='localhost'),
        'PORT': config('DATABASE_PORT',default='5432'),
    }
}

#Email config
EMAIL_BACKEND = config("EMAIL_BACKEND")
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_HOST_USER = config('EMAIL_HOST_USER')  
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD') 
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL=config('DEFAULT_FROM_EMAIL',EMAIL_HOST_USER)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'app_auth.User'
LOGIN_URL = '/account/login/'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Havana'

USE_L10N = True

USE_I18N = True

USE_TZ = True

LANGUAGES = [
  ('es', 'Español'),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = 'media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
PRIVATE_STORAGE_ROOT = os.path.join(BASE_DIR, 'private')
PRIVATE_STORAGE_URL = '/private/'
PRIVATE_STORAGE_AUTH_FUNCTION='private_storage.permissions.allow_superuser'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SITE_NAME = "TRD Caribe"

UNFOLD = {
    "SITE_TITLE": "TRD Caribe",
    "SITE_HEADER": "TRD Caribe",
    "SITE_SUBHEADER": _("Proyecto Escolar"),
    "SITE_SYMBOL":"local_mall",
    "SITE_URL": "/",
    "SHOW_BACK_BUTTON": True,
    "DASHBOARD_CALLBACK": "app_statistics.views.dashboard_callback",
    "THEME": "light",
    "SIDEBAR": {
        "navigation": [
            {
                "items": [
                    {
                         "title": _("Dashboard"),
                         "icon": "dashboard", 
                         "link": reverse_lazy("admin:index"),
                    }
                ],
            },
            {
                "title": _("Configuración"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Localizaciones"),
                        "icon": "location_on",
                        "link": reverse_lazy("admin:app_config_province_changelist"),
                    },
                    {
                        "title": _("Quejas y Sugerencias"),
                        "icon": "person_alert",
                        "link": reverse_lazy("admin:app_config_contactrequest_changelist"),
                        "badge": "app_auth.utils.badge_callback",
                    }
                ],
            },
            {
                "title": _("Productos"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Productos"),
                        "icon": "package_2",
                        "link": reverse_lazy("admin:app_products_products_changelist"),
                    },
                    {
                        "title": _("Categorías"),
                        "icon": "category",
                        "link": reverse_lazy("admin:app_products_category_changelist"),
                    },
                    {
                        "title": _("Reseñas"),
                        "icon": "reviews",
                        "link": reverse_lazy("admin:app_products_reviews_changelist"),
                    },
                ],
            },
            {
                "title": _("Tienda"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Facturas"),
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:app_store_invoices_changelist"),
                    },
                ],
            },
            {
                "title": _("Usuarios & Grupos"),
                "collapsible": True,
                "items": [
                    {
                        "title": _("Clientes"),
                        "icon": "people",
                        "link": reverse_lazy("admin:app_auth_user_changelist"),
                    },
                    {
                        "title": _("Trabajadores"),
                        "icon": "people",
                        "link": reverse_lazy("admin:app_auth_worker_changelist"),
                    },
                    {
                        "title": _("Grupos de Permisos"),
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            }
        ],
    },
    
}
