# Generated by Django 5.1.6 on 2025-05-31 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestatistics',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
