# Generated by Django 5.1.6 on 2025-06-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_statistics', '0002_alter_salestatistics_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestatistics',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
